### ISSUE TITLE
That's bruh, dude

### ISSUE THREAD

**Issue by nillerusr** [nn-firc/csgo-sdk-2017#5]
![FCZ6gJOXMAYMCEB](https://user-images.githubusercontent.com/42746659/215563914-d2f8e058-2966-4325-80b1-d3bca1658448.png)

**Comment by nn-firc** [comment]
yeah

**Comment by nn-firc** [comment]
ur right

**Comment by nn-firc** [comment]
ur mum

**Comment by stephen-cusi** [comment]
Хочешь 10 штук "Катюши"?
